import { LIMITS } from '@flare/contracts';
import { z } from 'zod';
import { ApiError } from '../lib/errors';

/**
 * Bindings and variables the Worker expects. `Env` itself is generated by `wrangler types`
 * from wrangler.jsonc; this file layers validation and defaults on top of it.
 */
export type AppBindings = Env;

const DEFAULT_MODELS = {
  stt: 'openai/whisper-large-v3-turbo',
  llm: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
  tts: 'hexgrad/Kokoro-82M',
} as const;

const configSchema = z.object({
  appVersion: z.string().default('dev'),
  allowedOrigins: z.array(z.string()),
  dailyTurnLimit: z.number().int().positive(),
  clerk: z
    .object({
      jwtKey: z.string().optional(),
      secretKey: z.string().optional(),
    })
    .refine((c) => Boolean(c.jwtKey || c.secretKey), {
      message: 'Set CLERK_JWT_KEY (preferred) or CLERK_SECRET_KEY',
    }),
  deepinfra: z.object({
    apiKey: z.string().min(1),
    sttModel: z.string().min(1),
    llmModel: z.string().min(1),
    ttsModel: z.string().min(1),
  }),
  turnstileSecretKey: z.string().optional(),
});

export type AppConfig = z.infer<typeof configSchema>;

function nonEmpty(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
}

/** Splits `ALLOWED_ORIGINS` (comma separated) into a clean list. */
export function parseAllowedOrigins(value: string | undefined): string[] {
  return (value ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Builds the validated config once per request. Missing secrets surface as a clear
 * `not_configured` error instead of an obscure upstream failure later in the pipeline.
 */
export function loadConfig(env: AppBindings): AppConfig {
  const dailyTurnLimit = Number.parseInt(nonEmpty(env.DAILY_TURN_LIMIT) ?? '', 10);

  const result = configSchema.safeParse({
    appVersion: nonEmpty(env.APP_VERSION),
    allowedOrigins: parseAllowedOrigins(env.ALLOWED_ORIGINS),
    dailyTurnLimit: Number.isFinite(dailyTurnLimit) ? dailyTurnLimit : LIMITS.dailyTurnsDefault,
    clerk: {
      jwtKey: nonEmpty(env.CLERK_JWT_KEY)?.replace(/\\n/g, '\n'),
      secretKey: nonEmpty(env.CLERK_SECRET_KEY),
    },
    deepinfra: {
      apiKey: nonEmpty(env.DEEPINFRA_API_KEY),
      sttModel: nonEmpty(env.DEEPINFRA_STT_MODEL) ?? DEFAULT_MODELS.stt,
      llmModel: nonEmpty(env.DEEPINFRA_LLM_MODEL) ?? DEFAULT_MODELS.llm,
      ttsModel: nonEmpty(env.DEEPINFRA_TTS_MODEL) ?? DEFAULT_MODELS.tts,
    },
    turnstileSecretKey: nonEmpty(env.TURNSTILE_SECRET_KEY),
  });

  if (!result.success) {
    const problems = result.error.issues.map(
      (i) => `${i.path.join('.') || 'config'}: ${i.message}`
    );
    throw new ApiError('not_configured', 'The API is missing required configuration.', {
      details: problems,
      expose: false,
    });
  }

  return result.data;
}
